# Project
version=0.2.3+alpha-26.1.2
group=com.axalotl.async
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Async
mod_author=AxalotL, Alchemy, Bliss, FurryMileon, Grider, jediminer543
mod_id=async
description=Async-Minecraft Entity Multi-Threading Mod
minecraft_version_range=[26.1.2]

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.152.1+26.1.2
fabric_loader_version=0.19.3

# NeoForge
# https://neoforged.net/
neoforge_version=26.1.2.76
neoforge_loader_version_range=[1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# API Dependencies
permission_api=0.7.0
lithium_version=mc26.1.2-0.24.6

# Mixin squared
mixinsquared_version=0.3.3