# Project
version=0.2.1+alpha-26.1
group=com.axalotl.async
java_version=25

# Common
minecraft_version=26.1
mod_name=Async
mod_author=AxalotL, Alchemy, Bliss, FurryMileon, Grider, jediminer543
mod_id=async
license=GPL-3.0
credits=
description=Async-Minecraft Entity Multi-Threading Mod
minecraft_version_range=[26.1]

# Fabric
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4

# NeoForge
neoforge_version=26.1.0.1-beta
neoform_version=26.1-1
neoforge_loader_version_range=[1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# API Dependencies
permission_api=0.6.1
lithium_version=mc26.1-0.22.0

# Mixin versions
mixin_version=0.8.7
mixin_min_version=0.8.5
mixinextras_version=0.5.3
mixinsquared_version=0.3.3