plugins {
    id 'idea'
    id 'net.fabricmc.fabric-loom'
}

repositories {
    maven { url = 'https://maven.bawnorton.com/releases' }
    maven { url 'https://api.modrinth.com/maven' }
}

dependencies {
    minecraft("com.mojang:minecraft:${minecraft_version}")
    compileOnly("net.fabricmc:fabric-loader:$fabric_loader_version")
    compileOnly "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${mixinsquared_version}"))
    implementation("org.ow2.asm:asm:9.6")
    implementation("org.ow2.asm:asm-tree:9.6")
    compileOnly 'org.projectlombok:lombok:1.18.44'
    annotationProcessor 'org.projectlombok:lombok:1.18.44'
    implementation "maven.modrinth:lithium:${lithium_version}-neoforge"
}

loom {
    mixin {
        defaultRefmapName = "async.refmap.json"
        useLegacyMixinAp = false
    }
    accessWidenerPath = file("src/main/resources/async.accesswidener")
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}