modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "GPL-3.0"

[[mods]]
modId = "async"
version = "${version}"
displayName = "Async"

logoFile = "async/icon.png"
authors = "AxalotL, Alchemy, Bliss, FurryMileon, Grider, jediminer543"
description = '''${description}'''

[[mixins]]
config = "async.common.mixins.json"

[[mixins]]
config = "async.neoforge.mixins.json"

[[dependencies.async]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.async]]
modId = "moonrise"
type = "incompatible"
versionRange = ""
ordering = "NONE"
side = "BOTH"

[[dependencies.async]]
modId = "openpartiesandclaims"
type = "incompatible"
versionRange = ""
ordering = "NONE"
side = "BOTH"

["lithium:options"]
"mixin.alloc.chunk_random" = false
"mixin.ai.task.memory_change_counting" = false