package com.axalotl.async.api.fastutil;

import it.unimi.dsi.fastutil.Hash;
import it.unimi.dsi.fastutil.HashCommon;
import it.unimi.dsi.fastutil.longs.*;
import org.jetbrains.annotations.NotNull;

import java.util.*;
import java.util.concurrent.ConcurrentSkipListSet;

/**
 * Thread-safe implementation of LongLinkedOpenHashSet using ConcurrentSkipListSet as backing storage.
 * This implementation provides concurrent access and maintains elements in sorted order.
 *
 * <p>
 * A type-specific linked hash set with a fast, small-footprint implementation.
 *
 * <p>
 * Instances of this class use a hash table to represent a set. The table is filled up to a
 * specified <em>load factor</em>, and then doubled in size to accommodate new entries. If the table
 * is emptied below <em>one fourth</em> of the load factor, it is halved in size; however, the table
 * is never reduced to a size smaller than that at creation time: this approach makes it possible to
 * create sets with a large capacity in which insertions and deletions do not cause immediately
 * rehashing. Moreover, halving is not performed when deleting entries from an iterator, as it would
 * interfere with the iteration process.
 *
 * <p>
 * Note that {@link #clear()} does not modify the hash table size. Rather, a family of
 * {@linkplain #trim() trimming methods} lets you control the size of the table; this is
 * particularly useful if you reuse instances of this class.
 *
 * <p>
 * Iterators generated by this set will enumerate elements in the same order in which they have been
 * added to the set (addition of elements already present in the set does not change the iteration
 * order). Note that this order has nothing in common with the natural order of the keys. The order
 * is kept by means of a doubly linked list, represented <i>via</i> an array of longs parallel to
 * the table.
 *
 * <p>
 * This class implements the interface of a sorted set, so to allow easy access of the iteration
 * order: for instance, you can get the first element in iteration order with {@code first()}
 * without having to create an iterator; however, this class partially violates the
 * {@link java.util.SortedSet} contract because all subset methods throw an exception and
 * {@link #comparator()} returns always {@code null}.
 *
 * <p>
 * Additional methods, such as {@code addAndMoveToFirst()}, make it easy to use instances of this
 * class as a cache (e.g., with LRU policy).
 *
 * <p>
 * The iterators provided by this class are type-specific {@linkplain java.util.ListIterator list
 * iterators}, and can be started at any element <em>which is in the set</em> (if the provided
 * element is not in the set, a {@link NoSuchElementException} exception will be thrown). If,
 * however, the provided element is not the first or last element in the set, the first access to
 * the list index will require linear time, as in the worst case the entire set must be scanned in
 * iteration order to retrieve the positional index of the starting element. If you use just the
 * methods of a type-specific {@link it.unimi.dsi.fastutil.BidirectionalIterator}, however, all
 * operations will be performed in constant time.
 *
 * @see Hash
 * @see HashCommon
 */
public class ConcurrentLongLinkedOpenHashSet extends LongLinkedOpenHashSet {

    /**
     * Thread-safe sorted backing set used for storing Long values.
     * Delegates concurrency and ordering to ConcurrentSkipListSet.
     */
    private final ConcurrentSkipListSet<Long> backing = new ConcurrentSkipListSet<>();

    /**
     * Creates an empty set.
     */
    public ConcurrentLongLinkedOpenHashSet() {
    }

    @Override
    public boolean add(final long k) {
        return backing.add(k);
    }

    @Override
    public boolean addAll(Collection<? extends Long> c) {
        Objects.requireNonNull(c, "Collection cannot be null");
        return backing.addAll(c);
    }

    @Override
    public boolean contains(final long k) {
        return backing.contains(k);
    }

    @Override
    public boolean remove(final long k) {
        return backing.remove(k);
    }

    @Override
    public void clear() {
        backing.clear();
    }

    @Override
    public boolean isEmpty() {
        return backing.isEmpty();
    }

    @Override
    public int size() {
        return backing.size();
    }

    /**
     * Returns the first element of this set in iteration order.
     *
     * @return the first element in iteration order.
     */
    @Override
    public long firstLong() {
        return Optional.ofNullable(backing.first())
                .orElseThrow(() -> new NoSuchElementException("Set is empty"));
    }

    /**
     * Returns the last element of this set in iteration order.
     *
     * @return the last element in iteration order.
     */
    @Override
    public long lastLong() {
        return Optional.ofNullable(backing.last())
                .orElseThrow(() -> new NoSuchElementException("Set is empty"));
    }

    /**
     * Removes the first key in iteration order.
     *
     * @return the first key.
     */
    @Override
    public long removeFirstLong() {
        long first = firstLong();
        backing.remove(first);
        return first;
    }

    /**
     * Removes the last key in iteration order.
     *
     * @return the last key.
     */
    @Override
    public long removeLastLong() {
        long last = lastLong();
        backing.remove(last);
        return last;
    }

    @Override
    public @NotNull LongListIterator iterator() {
        return FastUtilHackUtil.wrap(backing.iterator());
    }

    @Override
    public boolean equals(Object obj) {
        return this == obj || (obj instanceof ConcurrentLongLinkedOpenHashSet other && backing.equals(other.backing));
    }

    @Override
    public int hashCode() {
        return backing.hashCode();
    }

    @Override
    public String toString() {
        return backing.toString();
    }
}
